service: proxy-api-transformer-fn

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1
  role: ${self:custom.config.lambdaRoleArn}
  environment:
    APP_ENV: ${self:custom.stage}
functions:
  abstraction:
    handler: src/handler.init
    environment:
      BASE_URL: ${self:custom.config.baseUrl}
    events:
     - httpApi:
         path: /{proxy+}
         method: any

plugins:
  - serverless-offline

